### ISSUE TITLE
Matches should be uniform

### ISSUE THREAD

**Issue by AshiraFriedman** [shanaglazer/memory#5]
It can be confusing for the player that the matches are an uppercase and lowercase letter.  The cards should be uniform to be a match - all uppercase or lowercase.

**Comment by shanaglazer** [comment]
When I decided on this game I thought of doing it for an educational purpose - matching an uppercase letter to a lowercase one - I did it that way on purpose. Can I leave it this way?

**Comment by AshiraFriedman** [comment]
If you had a specific goal in mind, that's fine
